# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{summarizer}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christoph Petschnig"]
  s.date = %q{2010-01-25}
  s.description = %q{Make sums and subtotals of your database tables}
  s.email = %q{info@purevirtual.de}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "MIT-LICENSE",
     "Manifest.txt",
     "PostInstall.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/summarizer.rb",
     "lib/summarizer/add_it_up.rb",
     "lib/summarizer/base.rb",
     "script/console",
     "script/destroy",
     "script/generate",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/summarizer_spec.rb",
     "tasks/rspec.rake",
     "test/test_helper.rb",
     "test/test_summarizer.rb"
  ]
  s.homepage = %q{http://github.com/ChristophPetschnig/summarizer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Make totals and sub-totals of your tables}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/summarizer_spec.rb",
     "test/test_summarizer.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

